### ISSUE TITLE
Don't strip href

### ISSUE THREAD

**Issue by john-kurkowski** [rynam0/ember-swagger-ui#6]
First off, I'm really happy to discover this addon. swagger-ui leaves something to be desired in SPA-land. This is a handy integration I didn't want to bootstrap myself. Thank you!

I'm having trouble with [swagger-ui.js#L69-L73](https://github.com/rynam0/ember-swagger-ui/blob/16cefc968fd73a68e12578fd21274fe5b52ed84f/addon/components/swagger-ui.js#L69-L73):

```javascript
        // and remove href links that will also attempt to route us out of our known ember routes
        let anchors = that.$('#resources_container a');
        if (anchors) {
          anchors.removeAttr('href');
        }
```

This makes external links unclickable. Can't have the whole world in my Ember app :). I'm missing its original intent. [I've deleted it in my fork](https://github.com/john-kurkowski/ember-swagger-ui/tree/restore-hrefs), but I don't think that's the answer. Could you explain your code comment more? 

Can you restore links? Or warn if they'll route you outside the app? Or make it configurable? (Not that swagger-ui needs yet another input param.)

**Comment by rynam0** [comment]
Glad to hear someone else is giving this a go and thanks for reporting the issue.

The reason I decided to remove the href attributes inside the resources_container was that swagger-ui added hash-bang urls (as can be seen in the screenshot below).  Clicking to expand/collapse the docs caused the url to update to an unknown ember route (#!/pets in the example).  I don't know if this only happens when using locationType: 'hash' in environment.js but I could certainly explore that some more.

It may also be possible to remove specific href attributes leaving your external links intact.  An example of a swagger.json file that demonstrates the issue would be super.  If you could supply one I would be more than happy to take a look.

![screen shot 2015-11-25 at 4 27 55 pm](https://cloud.githubusercontent.com/assets/1716753/11410065/70f5ebaa-9392-11e5-8d1d-571151b407bd.png)

**Comment by john-kurkowski** [comment]
My use case is similar to the http://swagger.io and mailto links in your screenshot. Those `href`s are fine, left alone by ember-swagger-ui. But here's a fork of Pet Store with a link in one of the description fields, supporting GFM: [Gist](https://gist.github.com/john-kurkowski/1665fb585e2520383d32/revisions) / [raw](https://gist.githubusercontent.com/john-kurkowski/1665fb585e2520383d32/raw/ce478dc33aa4518644c627735d1b50f401ba79bd/petstore.json). Its `href` is stripped out.

I see your use case now. I'm using an extension of the `history` location type, not `hash`. Maybe you can refine the selector based on the above example doc. Additionally, you could only disable the links if the app is using an extension of the `hash` location type.

**Comment by rynam0** [comment]
@john-kurkowski: Thanks for the example spec file.  I'm oddly enough unable to reproduce the issue in my project after removing the code in question.  I think it best not to remove the href attributes as the component could be extended to remove problematic hrefs if needed.  I don't think this component should make  assumptions and remove them by default.  Thanks again for reporting this.

**Comment by john-kurkowski** [comment]
That works too! Thanks!
